package com.ufes.sistema.view;

import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

public class AlterarSenhaView extends JInternalFrame {
    public AlterarSenhaView() {
        initComponents();
    }

    public javax.swing.JButton getBtnSalvar() {
        return btnSalvar;
    }

    public javax.swing.JButton getBtnFechar() {
        return btnFechar;
    }

    public String getSenhaAtual() {
        return new String(txtSenhaAtual.getPassword());
    }

    public String getNovaSenha() {
        return new String(txtNovaSenha.getPassword());
    }

    public String getConfirmacaoSenha() {
        return new String(txtConfirmacao.getPassword());
    }

    public void limparCampos() {
        txtSenhaAtual.setText("");
        txtNovaSenha.setText("");
        txtConfirmacao.setText("");
    }

    public void limparECorrigirFoco() {
        SwingUtilities.invokeLater(() -> {

            this.limparCampos();

            
            txtSenhaAtual.requestFocusInWindow();

            
            this.revalidate();
            this.repaint();
        });
    }

    public void mostrarMensagem(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    public void fechar() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAtual = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JPasswordField();
        lblNova = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        lblConfirmacao = new javax.swing.JLabel();
        txtConfirmacao = new javax.swing.JPasswordField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        lblAtual.setText("Senha Atual:");

        lblNova.setText("Nova Senha:");

        txtNovaSenha.addActionListener(this::txtNovaSenhaActionPerformed);

        lblConfirmacao.setText("        Confirmar  senha:");

        btnFechar.setText("Fechar");

        btnSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFechar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNova)
                        .addComponent(lblAtual))
                    .addComponent(lblConfirmacao))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtual)
                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNova)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblAtual;
    private javax.swing.JLabel lblConfirmacao;
    private javax.swing.JLabel lblNova;
    private javax.swing.JPasswordField txtConfirmacao;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtSenhaAtual;
    // End of variables declaration//GEN-END:variables
}
