package com.ufes.sistema.view;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;

import com.ufes.sistema.model.Usuario;
import javax.swing.JInternalFrame;
import javax.swing.ListSelectionModel;

public class EnviarNotificacaoView extends JInternalFrame {
    
    private static final java.util.logging.Logger logger = Logger.getLogger(EnviarNotificacaoView.class.getName());

    private List<Usuario> usuariosNaTabela;
    
    public EnviarNotificacaoView() {
        initComponents();
        this.usuariosNaTabela = new ArrayList<>();
        this.tblUsuarios.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    public JButton getBtnEnviar() {
        return btnEnviar;
    }
    
    public JButton getBtnFechar() {
        return btnFechar;
    }
    
    public String getMensagem() {
        return txtMensagem.getText(); 
    }
    
    public List<Usuario> getUsuariosSelecionados() {
        List<Usuario> selecionados = new ArrayList<>();
        int[] linhasSelecionadas = tblUsuarios.getSelectedRows();

        for (int i : linhasSelecionadas) {
            if (i >= 0 && i < usuariosNaTabela.size()) {
                selecionados.add(usuariosNaTabela.get(i));
            }
        }
        return selecionados;
    }

    public void carregarUsuarios(List<Usuario> usuarios) {
        this.usuariosNaTabela = usuarios;
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        model.setRowCount(0);

        for (Usuario u : usuarios) {
            model.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.isAutorizado() ? "Sim" : "Não" 
            });
        }
    }
    
    public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public void limparCampos() {
        txtMensagem.setText("");
        tblUsuarios.clearSelection();
    }
    
    public void fechar() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDestinatarios = new javax.swing.JLabel();
        scrUsuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        scrMensagem = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Enviar Notificação");

        lblDestinatarios.setText("Destinatários");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Autorizado"
            }
        ));
        scrUsuarios.setViewportView(tblUsuarios);

        lblMensagem.setText("Mensagem");

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        scrMensagem.setViewportView(txtMensagem);

        btnEnviar.setText("Enviar");

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDestinatarios)
                            .addComponent(scrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar)
                                .addGap(39, 39, 39)
                                .addComponent(btnFechar))
                            .addComponent(lblMensagem)
                            .addComponent(scrMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(lblTitulo)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addComponent(lblDestinatarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviar)
                            .addComponent(btnFechar))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblDestinatarios;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrMensagem;
    private javax.swing.JScrollPane scrUsuarios;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables
}
