/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ufes.sistema.view;

import javax.swing.*;

/**
 *
 * @author Guiguito
 */
public class ManterUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManterUsuarioView
     */
    public ManterUsuarioView() {
        initComponents();
        this.setClosable(true); 
        this.setResizable(true);
        this.setTitle("Gestão de Usuários");
    }
    
    public JTable getTabela() { return tblUsuarios; }
    public JButton getBtnAutorizar() { return btnAutorizar; }
    public JButton getBtnTornarAdmin() { return btnTornarAdmin; }
    public JButton getBtnExcluir() { return btnExcluir; }
    public JButton getBtnCriarNovoUsuario() { return btnCriarNovoUsuario; }

    public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public int getLinhaSelecionada() {
        return tblUsuarios.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnAutorizar = new javax.swing.JButton();
        btnCriarNovoUsuario = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnTornarAdmin = new javax.swing.JButton();

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnAutorizar.setText("Autorizar");

        btnCriarNovoUsuario.setText("Criar novo Usuário");

        btnExcluir.setText("Excluir");

        btnTornarAdmin.setText("Tornar Administrador/Usuário");
        btnTornarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTornarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAutorizar)
                        .addGap(95, 95, 95)
                        .addComponent(btnTornarAdmin)
                        .addGap(104, 104, 104)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCriarNovoUsuario))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutorizar)
                    .addComponent(btnCriarNovoUsuario)
                    .addComponent(btnExcluir)
                    .addComponent(btnTornarAdmin))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTornarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTornarAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTornarAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnCriarNovoUsuario;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnTornarAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
