package com.ufes.sistema.view;

import com.ufes.sistema.model.Notificacao;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class MinhasNotificacoesView extends JInternalFrame {

    public MinhasNotificacoesView() {
        initComponents();
    }

    public JButton getBtnMarcarLida() {
        return btnMarcarLida;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JTable getTblNotificacoes() {
        return tblNotificacoes;
    }

    public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public void fechar() {
        this.dispose();
    }

    public void carregarTabela(List<Notificacao> lista) {
        DefaultTableModel model = (DefaultTableModel) tblNotificacoes.getModel();
        model.setRowCount(0);
        for (Notificacao n : lista) {
            model.addRow(new Object[]{
                n.getId(),
                n.getConteudo(),
                n.getDataEnvio().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"))
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        scrLista = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotificacoes = new javax.swing.JTable();
        btnMarcarLida = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Minhas Notificações");

        tblNotificacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Mensagem", "Data"
            }
        ));
        jScrollPane1.setViewportView(tblNotificacoes);

        scrLista.setViewportView(jScrollPane1);

        btnMarcarLida.setText("Marcar como lida");
        btnMarcarLida.addActionListener(this::btnMarcarLidaActionPerformed);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(this::btnFecharActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMarcarLida)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar))
                            .addComponent(scrLista, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addComponent(scrLista, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarLida)
                    .addComponent(btnFechar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarLidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarLidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarLidaActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnMarcarLida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrLista;
    private javax.swing.JTable tblNotificacoes;
    // End of variables declaration//GEN-END:variables
}
