package com.ufes.sistema.view;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JLabel;
import javax.swing.JFrame;

public class PrincipalView extends JFrame {
    
    public PrincipalView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
   public JDesktopPane getDesktopPane() { return desktopPane; }
    
   
    public JMenu getMnuAdministracao() { return mnuAdministracao; }
    public JMenuItem getMitManterUsuarios() { return mitManterUsuarios; } 
    public JMenuItem getMitEnviarNotificacao() { return mitEnviarNotificacao; } 
    public JMenuItem getMitConfigurarLog() { return mitConfigurarLog; } 
    public JMenuItem getMitAlterarSenha() { return mitAlterarSenha; } 
    public JMenuItem getMitSair() { return mitSair; }
    public JMenuItem getMitRestaurarSistema(){ return mitRestaurarSistema;}
    public JLabel getLblUsuario() { return lblUsuario; }
    public JButton getBtnNotificacoes() { return btnNotificacoes; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnNotificacoes = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracao = new javax.swing.JMenu();
        mitManterUsuarios = new javax.swing.JMenuItem();
        mitEnviarNotificacao = new javax.swing.JMenuItem();
        mitConfigurarLog = new javax.swing.JMenuItem();
        mitRestaurarSistema = new javax.swing.JMenuItem();
        mnuMinhaConta = new javax.swing.JMenu();
        mitAlterarSenha = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mitSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Usuários");
        setExtendedState(6);
        setFocusCycleRoot(false);

        lblUsuario.setText("Usuário:  Carregando...");

        btnNotificacoes.setText("0 Notificações");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(129, 129, 129)
                .addComponent(btnNotificacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(btnNotificacoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        mnuAdministracao.setText("Administração");

        mitManterUsuarios.setText("Manter Usuários");
        mnuAdministracao.add(mitManterUsuarios);

        mitEnviarNotificacao.setText("Enviar Notificação");
        mnuAdministracao.add(mitEnviarNotificacao);

        mitConfigurarLog.setText("Configurar Log");
        mnuAdministracao.add(mitConfigurarLog);

        mitRestaurarSistema.setText("Restaurar Sistema");
        mnuAdministracao.add(mitRestaurarSistema);

        jMenuBar1.add(mnuAdministracao);

        mnuMinhaConta.setText("Minha Conta");

        mitAlterarSenha.setText("Alterar Senha");
        mnuMinhaConta.add(mitAlterarSenha);
        mnuMinhaConta.add(jSeparator2);

        mitSair.setText("Sair");
        mnuMinhaConta.add(mitSair);

        jMenuBar1.add(mnuMinhaConta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mitAlterarSenha;
    private javax.swing.JMenuItem mitConfigurarLog;
    private javax.swing.JMenuItem mitEnviarNotificacao;
    private javax.swing.JMenuItem mitManterUsuarios;
    private javax.swing.JMenuItem mitRestaurarSistema;
    private javax.swing.JMenuItem mitSair;
    private javax.swing.JMenu mnuAdministracao;
    private javax.swing.JMenu mnuMinhaConta;
    // End of variables declaration//GEN-END:variables
}
