 package com.ufes.sistema.view;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class RestaurarSistemaView extends JInternalFrame {

    public RestaurarSistemaView() {
        initComponents();
        this.setClosable(true);
        this.setTitle("Restauração Completa do Sistema");
    }
    
    public String getSenhaAtual(){
        return new String(txtSenhaAtual.getPassword());
    }
    
    public String getConfirmarSenhaAtual(){
        return new String(txtConfirmarSenhaAtual.getPassword());
    }
    
    public JButton getBtnRestaurarSistema(){
        return btnRestaurarSistema;
    }
    
    public void mostrarMensagem(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public void fechar(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtConfirmarSenhaAtual = new javax.swing.JPasswordField();
        txtSenhaAtual = new javax.swing.JPasswordField();
        lblSenhaAtual = new javax.swing.JLabel();
        lblConfirmarSenhaAtual = new javax.swing.JLabel();
        btnRestaurarSistema = new javax.swing.JButton();
        lblTituloJanela = new javax.swing.JLabel();

        lblSenhaAtual.setText("Senha Atual");

        lblConfirmarSenhaAtual.setText("Confirmar Senha Atual");

        btnRestaurarSistema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRestaurarSistema.setForeground(new java.awt.Color(238, 75, 43));
        btnRestaurarSistema.setText("RESTAURAR SISTEMA");
        btnRestaurarSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 38, 75)));

        lblTituloJanela.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloJanela.setText("Restauração do Sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfirmarSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConfirmarSenhaAtual)
                            .addComponent(lblSenhaAtual)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnRestaurarSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblTituloJanela)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloJanela)
                .addGap(118, 118, 118)
                .addComponent(lblSenhaAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblConfirmarSenhaAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmarSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRestaurarSistema)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestaurarSistema;
    private javax.swing.JLabel lblConfirmarSenhaAtual;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblTituloJanela;
    private javax.swing.JPasswordField txtConfirmarSenhaAtual;
    private javax.swing.JPasswordField txtSenhaAtual;
    // End of variables declaration//GEN-END:variables
}
